# Generated by Django 3.2.9 on 2021-12-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='time_created',
            new_name='date_created',
        ),
    ]
