# Generated by Django 3.2.9 on 2021-12-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0002_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
